### ISSUE TITLE
Currency amounts should not be floats

### ISSUE THREAD

**Issue by riptl** [redmaner/go-nimiq-rpc#1]
Thanks a lot for creating a Go client for the Nimiq RPC interface. This will be helpful in the future!
I will be creating a few issues + PRs with suggestions with minor things I noticed.

Floating point numbers are prone to rounding errors (try `python3 -c "print(0.1 + 0.2)"` in your terminal). We make an effort to store currency amounts as integers where possible.

The types at

https://github.com/redmaner/go-nimiq-rpc/blob/08b72c2883c25e22e15f753696e859cd84e296a9/type.go#L48

and

https://github.com/redmaner/go-nimiq-rpc/blob/08b72c2883c25e22e15f753696e859cd84e296a9/type.go#L51

should be changed to `int64`s.

**Comment by redmaner** [comment]
Hi @terorie, you're welcome! I appreciate the feedback. I look forward to your other suggestions to further improve this library.

I am aware of the precision problem of floating point numbers. That's also the reason why I doubted if I would implement a type for NIM in the first place, and just stick to Luna only. I eventually choose to do so for convenience, accepting the risk of rounding errors. 

Regarding your proposal, changing NIM to a 64bit integer removes precision entirely. In my opinion this approach could be even more prone to errors. But this depends on what is acceptable, and what isn't. Maybe you could shed some light on this? I have tested both float64 and int64. You'll find the results below.

<b>As float64</b>
<code>./example --getBalance --addr "NQ52 V4BF 52J3 0PM6 BG4M 9QY1 RUYS UAL6 CJD2"</code>
<code>Balance raw: 2013660749</code>
<code>Balance in NIM: 20136.60749</code>
<code>Balance in Luna: 2013660748</code>
With this example you'll will see that the initial conversion to NIM succeeds without errors. Converting it back to Luna leads to a rounding problem where you loose 1 luna of your balance. This isn't a 100% error free solution. Considering NIM will grow in the future, including balances, a floating point representation just doesn't suit the job if you want a 100% correct representation. 

<b>As int64</b>
<code>./example --getBalance --addr "NQ52 V4BF 52J3 0PM6 BG4M 9QY1 RUYS UAL6 CJD2"</code>
<code>Balance raw: 2013660749</code>
<code>Balance in NIM: 20136</code>
<code>Balance in Luna: 2013600000</code>
With this example I lost 60.749 Luna. This is the result of changing the types of float64 to int64 as you suggested. If you have any further suggestions to make it into an int64, that would be very welcome.

**Comment by riptl** [comment]
Losing precision isn't an option of course, we want all digits of precision :)
That is true, encoding `NIM` amounts in `int64` makes no sense. Good to see that Luna was already `int64` though.

> That's also the reason why I doubted if I would implement a type for NIM in the first place, and just stick to Luna only.

imho, that would be the best call in this case.
We would keep all values as `Luna`/`int64`s. It seems like the `NIM` type is rarely used anyways.

How about something like this?
```go
// FormatNIM formats a Luna value as a decimal in
// string representation with a dot separator `.`
// 
// Examples:
// FormatNIM(0) = "0"
// FormatNIM(100000) == "1"
// FormatNIM(1) = "0.00001"
// FormatNIM(1234567) = "12.34567"
func FormatNIM(l Luna) string { ... }
```

**Comment by redmaner** [comment]
I like your FormatNIM function proposal. I think it's the best way to address the issue of rounding errors, while still providing some functionality for Luna to NIM conversion. Not providing anything regarding to NIM might result in developers implementing their own conversion methods that have the same challenge: providing 100% correct precision. 

I'll see to implementing the NIM formatting function to replace the NIM type.

**Comment by redmaner** [comment]
Change implemented. Kept the NIM type around and changed it to string. Extensively tested various conversions from Luna to NIM and NIM to Luna. Also added a function to convert NIM back to Luna. 

Commit can be found here https://github.com/redmaner/go-nimiq-rpc/commit/5f3e3b4029b04b77850a2ddfebdcb25df0ac14f7

<i>Tested conversions which are working without (rounding) errors #EPIC: </i>
0 luna is 0 NIM
1 luna is 0.00001 NIM
100000 luna is 1 NIM
1234567 is 12.34567 NIM
1200000 is 12 NIM
123456789 is 1234.56789 NIM
0 NIM is 0 Luna
0.00001 NIM is 1 Luna
1 NIM is 100000 Luna
12.34567 NIM is 1234567 Luna
12 NIM is 1200000 Luna
1234.56789 NIM is 123456789 Luna
