### ISSUE TITLE
Use existing JSON-RPC implementation

### ISSUE THREAD

**Issue by riptl** [redmaner/go-nimiq-rpc#2]
Have you looked at the library https://github.com/ybbus/jsonrpc yet?
 
It has a few nice features:
 * Support for batch requests (doing multiple calls in one round-trip)
 * Flexibility: Options for custom HTTP transports and headers
 * Unit tests

**Comment by redmaner** [comment]
Honestly I have searched for existing JSON-RPC implementations in Go, but couldn't find an implementation that suited my needs. It's mostly a matter of preference, but I always choose simple and consistent libraries. Most libraries I found seemed to be overly complicated. Because JSON-RPC is pretty simple, it was just easier to implement it myself. 

I didn't stumble on the library you mentioned. I'll see if it has benefits to switch to this library, and if it can be incorporated without too much rework.

**Comment by riptl** [comment]
@redmaner Up to you I guess, but message batching is an important feature we use in prod. It shouldn't be too hard to add to your version. https://www.jsonrpc.org/specification#batch

**Comment by redmaner** [comment]
@terorie That's good to know! I'll see if I implement batching myself or if it is easier to switch to the library you mentioned

**Comment by riptl** [comment]
> Because JSON-RPC is pretty simple, it was just easier to implement it myself.

I agree with the sentiment, but it can be a bit harmful in some cases because details matter.
For example, our upcoming Rust implementation of the Nimiq core doesn't have the error codes set yet. This is a violation of the spec from our side, so go-nimiq-rpc fails to detect the errors and tries to read the (empty) result instead of returning the error message.

ybbus/jsonrpc (which boasts 1,5k LOC even if the protocol is pretty simple) is a bit more robust and considers this in a test (commented out but still passes):

```go
// only message in error is not ok, must at least contain code and message
responseBody = `{ "error": {"message": "something wrong"}}`
res, err = rpcClient.Call("something", 1, 2, 3)
<-requestChan
Expect(err).To(BeNil())
Expect(res.Result).To(BeNil())
Expect(res.Error).NotTo(BeNil())
```

**Comment by redmaner** [comment]
I'm already in the process of switching to the library :) 

Implementing batching myself or switching to the library was equal work, so choose to go for a well tested library instead of doing it myself this time.

**Comment by redmaner** [comment]
Succesfully switched. Also implemented the CallBatch functionality, and succesfully tested it.
