### ISSUE TITLE
Remove example, refactor as integration tests

### ISSUE THREAD

**Issue by riptl** [redmaner/go-nimiq-rpc#4]
While the example has a lot of features, there is already a powerful RPC client at https://github.com/nimiq/core-js/blob/master/doc/json-rpc-client.md

I suggest we keep a minimal example in `godoc` and remove `example/` to keep the library more manageable.

**Comment by redmaner** [comment]
Removal is probably best. I keep a copy locally, because it's pretty useful for testing purposes.

**Comment by riptl** [comment]
If you don't mind, you could rewrite it to an integration test, then the code isn't lost.
Obviously a node is required to test, so you could accept a `--connection` flag or similar in the test main (https://golang.org/pkg/testing/#hdr-Main) and skip the requests if the flag is missing (`t.Skip("No connection")`)
Totally fine if you don't do this though since it's a lot of work ...

**Comment by redmaner** [comment]
Refactoring the example as tests would be a good addition to the library. It's true that it would incorporate some work, but it also provides the ability to test the library  and to guarantee API level consistency in future releases.
