### ISSUE TITLE
Memory leak with HTTP response bodies

### ISSUE THREAD

**Issue by riptl** [redmaner/go-nimiq-rpc#5]
I was testing out this library in a production setting (upcoming Albatross visualizer) and I noticed the service was using 40 GB of memory an hour in :^) 
Closing the `http.Response.Body`s with defer fixed it.

Needs `defer httpResp.Body.Close()` (with error handling) on line 120
https://github.com/redmaner/go-nimiq-rpc/blob/5f3e3b4029b04b77850a2ddfebdcb25df0ac14f7/client.go#L116-L120

Also, this check is wrong.
godoc:
> // The http Client and Transport guarantee that Body is always
    // non-nil, even on responses without a body or responses with
    // a zero-length body. It is the caller's responsibility to
    // close Body.

https://github.com/redmaner/go-nimiq-rpc/blob/5f3e3b4029b04b77850a2ddfebdcb25df0ac14f7/client.go#L129-L132

**Comment by redmaner** [comment]
Fixed by switching to github.com/ybbus/jsonrpc for handling JSON-RPC
